#encoding:UTF-8
msg = 'www.BAIDU.com.123'
# print(msg.upper())  # upper()函数，将所有字母都转换成大写
# print(msg.lower())  # lower()函数，将所有字母都转换成小写
# print(msg.capitalize())  # capitalize()函数，将首字母都转换成大写，其余小写
# print(msg.title())  # title()函数，将每个单词的首字母都转换成大写，其余小写

title = '''
I.INTRODUCTION
II.VISION OF THE ISAC NETWORK
III.WAVEFORMS,RESOURCE ALLOCATION,AND CHANNEL PARAMETER ESTIMATION IN ISAC NETWORKS
IV.TECHNOLOGIES FOR JOINT BISTATIC AND MULTISTATIC SENSING AND COMMUNICATION
V.TECHNOLOGIES FOR JOINT MONOSTATIC SENSING AND COMMUNICATION
VI.SENSING AND COMMUNICATING WITH WIDE APERTURES
VII.TECHNOLOGIES FOR SENSING-ASSISTED COMMUNICATION
VIII.CONCLUSION
'''

print(title.title())

