#encoding:UTF-8
msg = 'www.BAIDU.com.123'
# print(msg.upper())  # upper()函数，将所有字母都转换成大写
# print(msg.lower())  # lower()函数，将所有字母都转换成小写
# print(msg.capitalize())  # capitalize()函数，将首字母都转换成大写，其余小写
# print(msg.title())  # title()函数，将每个单词的首字母都转换成大写，其余小写

title = '''
1 LINEAR REGRESSION WITH ONE PREDICTOR VARIABLE
2 INFERENCES IN REGRESSION AND CORRELATION ANALYSIS
3 DIAGNOSTICS AND REMEDIAL MEASURES 3-1
4 SIMULTANEOUS INFERENCES AND OTHER TOPICS IN REGRESSION ANALYSIS
5 MATRIX APPROACH TO SIMPLE LINEAR REGRESSION ANALYSIS
6 MULTIPLE REGRESSION
7 MULTIPLE REGRESSION
8 MODELS FOR QUANTITATIVE AND QUALITATIVE PREDICTORS
9 BUILDING THE REGRESSION MODEL I: MODEL SELECTION AND VALIDATION
10 BUILDING THE REGRESSION MODEL II: DIAGNOSTICS
11 BUILDING THE REGRESSION MODEL III: REMEDIAL MEASURES
12 AUTOCORRELATION IN TIME SERIES DATA
13 INTRODUCTION TO NONLINEAR REGRESSION AND NEURAL NETWORKS
14 LOGISTIC REGRESSION, POISSON REGRESSION,AND GENERALIZED LINEAR MODELS
15 INTRODUCTION TO THE DESIGN OF EXPERIMENTAL AND OBSERVATIONAL STUDIES
16 SINGLE-FACTOR STUDIES
17 ANALYSIS OF FACTOR LEVEL MEANS
18 ANOVA DIAGNOSTICS AND REMEDIAL MEASURES
19 TWO-FACTOR ANALYSIS OF VARIANCE WITH EQUAL SAMPLE SIZES
20 TWO-FACTOR STUDIES – ONE CASE PER TREATMENT
21 RANDOMIZED COMPLETE BLOCK DESIGNS
22 ANALYSIS OF COVARIANCE
23 TWO-FACTOR STUDIES WITH UNEQUAL SAMPLE SIZES
24 MULTIFACTOR STUDIES
25 RANDOM AND MIXED EFFECTS MODELS
26 NESTED DESIGNS, SUBSAMPLING, AND PARTIALLY NESTED DESIGN
27 REPEATED MEASURES AND RELATED DESIGNS
28 BALANCED INCOMPLETE BLOCK, LATIN SQUARE, AND RELATED DESIGNS
29 EXPLORATORY EXPERIMENTS – TWO-LEVEL FACTORIAL AND FRACTIONAL FACTORIAL DESIGNS
30 RESPONSE SURFACE METHODOLOGY
Appendix D: RULES FOR DEVELOPING ANOVA MODELS AND TABLES FOR BALANCED DESIGNS
'''

print(title.title())

