# Generated by Django 3.2.8 on 2022-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tencent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_job_name', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('duty', models.CharField(max_length=5000)),
                ('require', models.CharField(max_length=5000)),
                ('update_time', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tencent',
            },
        ),
    ]
